/**
 * GENERATED by scripts/embed-migrations.ts — do not edit.
 *
 * Each migration is compiled into the binary as text, so a single-file build
 * carries its own schema. Regenerate with `bun run db:generate`.
 */
import journalJson from "./migrations/meta/_journal.json" with { type: "json" };

import m0000FullSchema from "./migrations/0000_full_schema.sql" with { type: "text" };

/** Migration file name to its raw SQL, exactly as drizzle-kit wrote it. */
const files: Record<string, string> = {
  "0000_full_schema.sql": m0000FullSchema,
};

export interface EmbeddedJournalEntry { idx: number; when: number; tag: string; breakpoints: boolean }

export const embeddedJournal = journalJson as { version: string; dialect: string; entries: EmbeddedJournalEntry[] };
export const embeddedFiles = files;
export const embeddedMigrationCount: number = Object.keys(files).length;
