/**
 * GENERATED by scripts/embed-migrations.ts — do not edit.
 *
 * Each migration is compiled into the binary as text, so a single-file build
 * carries its own schema. Regenerate with `bun run db:generate`.
 */
import journalJson from "./migrations/meta/_journal.json" with { type: "json" };

import m0000FullSchema from "./migrations/0000_full_schema.sql" with { type: "text" };
import m0001RateLimits from "./migrations/0001_rate_limits.sql" with { type: "text" };
import m0002RateLimitExpiry from "./migrations/0002_rate_limit_expiry.sql" with { type: "text" };
import m0003StreamTickets from "./migrations/0003_stream_tickets.sql" with { type: "text" };
import m0004DeviceCredentials from "./migrations/0004_device_credentials.sql" with { type: "text" };
import m0005ChatHistory from "./migrations/0005_chat_history.sql" with { type: "text" };
import m0006RetireGowaEngineKind from "./migrations/0006_retire_gowa_engine_kind.sql" with { type: "text" };
import m0007Settings from "./migrations/0007_settings.sql" with { type: "text" };

/** Migration file name to its raw SQL, exactly as drizzle-kit wrote it. */
const files: Record<string, string> = {
  "0000_full_schema.sql": m0000FullSchema,
  "0001_rate_limits.sql": m0001RateLimits,
  "0002_rate_limit_expiry.sql": m0002RateLimitExpiry,
  "0003_stream_tickets.sql": m0003StreamTickets,
  "0004_device_credentials.sql": m0004DeviceCredentials,
  "0005_chat_history.sql": m0005ChatHistory,
  "0006_retire_gowa_engine_kind.sql": m0006RetireGowaEngineKind,
  "0007_settings.sql": m0007Settings,
};

export interface EmbeddedJournalEntry { idx: number; when: number; tag: string; breakpoints: boolean }

export const embeddedJournal = journalJson as { version: string; dialect: string; entries: EmbeddedJournalEntry[] };
export const embeddedFiles = files;
export const embeddedMigrationCount: number = Object.keys(files).length;
