/**
 * Generate the embedded-migration manifest.
 *
 * A compiled binary is a single file: `bun build --compile` bundles the
 * TypeScript and nothing else, so a relative migrations directory does not
 * exist beside the installed binary. The failure is silent — the manager sees
 * an empty folder, reports "no migration files found", and creates no tables at
 * all. Importing each .sql with `type: "text"` compiles it into the binary.
 *
 * The manifest is generated rather than hand-written so it cannot drift from
 * the journal, and this script fails loudly in both drift directions.
 *
 *   bun run scripts/embed-migrations.ts
 */
import { readdir } from "node:fs/promises";
import { join, relative } from "node:path";

// URL.pathname keeps percent-encoding, so a checkout under a path with a
// space or a "#" resolves to a directory that does not exist.
const ROOT = Bun.fileURLToPath(new URL("..", import.meta.url));
const MIGRATIONS_DIR = join(ROOT, "src/db/migrations");
const OUTPUT = join(ROOT, "src/db/migrations-embedded.ts");

interface JournalEntry { idx: number; when: number; tag: string; breakpoints: boolean }
interface Journal { version: string; dialect: string; entries: JournalEntry[] }

function fail(message: string): never {
  console.error(`✖ ${message}`);
  process.exit(1);
}

const journalPath = join(MIGRATIONS_DIR, "meta/_journal.json");
const journalFile = Bun.file(journalPath);
if (!(await journalFile.exists())) fail(`no journal at ${relative(ROOT, journalPath)} — run drizzle-kit generate`);

const journal = (await journalFile.json()) as Journal;

// An empty journal satisfies every drift check below, builds cleanly, and then
// exits at startup instead. Catch it here, where it is a generation fault.
if (journal.entries.length === 0) fail("journal lists no migrations — run drizzle-kit generate");

const onDisk = (await readdir(MIGRATIONS_DIR)).filter((f) => f.endsWith(".sql")).sort();
const inJournal = journal.entries.map((e) => `${e.tag}.sql`);

// Drift in either direction means the binary would ship a manifest that lies
// about what it can run.
const missing = inJournal.filter((f) => !onDisk.includes(f));
if (missing.length > 0) fail(`journal names migrations that are not on disk: ${missing.join(", ")}`);

const unlisted = onDisk.filter((f) => !inJournal.includes(f));
if (unlisted.length > 0) fail(`migrations on disk are absent from the journal: ${unlisted.join(", ")}`);

/** `0001_odd_name.sql` → `m0001OddName`, a valid identifier. */
function identifier(tag: string): string {
  const camel = tag.replace(/[^A-Za-z0-9]+(.)?/g, (_, c: string | undefined) => (c ? c.toUpperCase() : ""));
  return `m${camel.charAt(0).toUpperCase()}${camel.slice(1)}`;
}

const imports = journal.entries
  .map((e) => `import ${identifier(e.tag)} from "./migrations/${e.tag}.sql" with { type: "text" };`)
  .join("\n");

const entries = journal.entries
  .map((e) => `  ${JSON.stringify(`${e.tag}.sql`)}: ${identifier(e.tag)},`)
  .join("\n");

const output = `/**
 * GENERATED by scripts/embed-migrations.ts — do not edit.
 *
 * Each migration is compiled into the binary as text, so a single-file build
 * carries its own schema. Regenerate with \`bun run db:generate\`.
 */
import journalJson from "./migrations/meta/_journal.json" with { type: "json" };

${imports}

/** Migration file name to its raw SQL, exactly as drizzle-kit wrote it. */
const files: Record<string, string> = {
${entries}
};

export interface EmbeddedJournalEntry { idx: number; when: number; tag: string; breakpoints: boolean }

export const embeddedJournal = journalJson as { version: string; dialect: string; entries: EmbeddedJournalEntry[] };
export const embeddedFiles = files;
export const embeddedMigrationCount: number = Object.keys(files).length;
`;

await Bun.write(OUTPUT, output);
console.log(`✓ embedded ${journal.entries.length} migration(s) → ${relative(ROOT, OUTPUT)}`);
